[package]
name = "gtk-todo"
version = "0.1.0"
edition = "2018"

[dependencies]
async-channel = "1.6"
cascade = "1.0"
fomat-macros = "0.3"
gio = "0.9"
glib = "0.10"
gtk = { version = "0.9", features = ["v3_22"] }
slotmap = "1.0"
xdg = "2.2"
